#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --config $HOME/.config/picom/picom.conf &

bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
bspc monitor DP1 -d   

feh --bg-fill --randomize ~/wallpapers/*
killall -q polybar 
polybar laptop & 
polybar vga

bspc config border_width  	1 
bspc config window_gap	 	0	
bspc config top_padding		20	

bspc config single_monocle true
bspc config split_ratio          0.69
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color  "#101010"
bspc config normal_border_color  "#1a1a1a"
bspc config -d II window_gap 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a ranger state=floating rectangle=1000x500+0+0 center=on
bspc rule -a kitten state=floating rectangle=600x440+0+0 center=on
bspc rule -a imv desktop='^3' state=floating center=on
bspc rule -a mpv desktop='^3' state=floating center=on
bspc rule -a neovim state=floating rectangle=1400x900+0+0 center=on

xsetroot -cursor_name left_ptr


