#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
picom --config $HOME/.config/picom/picom.conf &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        1 
bspc config window_gap	 	0 
bspc config top_padding		0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color  "#1a1a1a"
bspc config normal_border_color  "#1a1a1a"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a ranger state=floating rectangle=1000x500+0+0 center=on
bspc rule -a kitten state=floating rectangle=600x440+0+0 center=on
bspc rule -a imv state=floating center=on
bspc rule -a mpv state=floating center=on

xsetroot -cursor_name left_ptr


feh --bg-fill --randomize ~/wallpapers/*
killall -q polybar 
exec polybar
